# Generated by Django 4.2.5 on 2023-10-30 16:58

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='news/%Y/%m/%d/', verbose_name='Картинка превью')),
                ('text', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Текст новости')),
                ('title', models.CharField(blank=True, max_length=300, verbose_name='Заголовок')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Описание')),
                ('keywords', models.CharField(blank=True, max_length=300, verbose_name='Ключи')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'index_together': {('id', 'slug')},
            },
        ),
    ]
