# Generated by Django 4.2.4 on 2023-08-04 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nrgrade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='moneta',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='moneta',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='nrgrade.category'),
        ),
    ]
