# Generated by Django 4.2.4 on 2023-08-04 14:57

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('nrgrade', '0002_category_is_active_moneta_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneta',
            name='category',
            field=mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='moneta', to='nrgrade.category', verbose_name='Категория'),
        ),
    ]
