# Generated by Django 4.2.5 on 2023-09-13 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrgrade', '0004_alter_category_unique_together_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='years',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
    ]
