# Generated by Django 4.2.5 on 2023-09-14 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrgrade', '0005_category_years_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneta',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='qr_code'),
        ),
    ]
